# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180223_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.CharField(default='', max_length=200, verbose_name='课程公告'),
        ),
    ]
